site_name: Mixed Traffic Control
site_author: Yanzhi Yao, Anish Kulkarni, Yang Zheng

# Repository
repo_name: soc-ucsd/mixed-traffic
repo_url: https://github.com/soc-ucsd/mixed-traffic
edit_uri: edit/main/docs

# Copyright
copyright: Copyright &copy; 2022 SOC Lab

nav:
    - Welcome: index.md
    - Smoothing Traffic Flow: smoothing_traffic_flow.md
    - Structured Optimal Control: structured_optimal_control.md
    - Cooperative Formation Multiple: cooperative_formation_multiple.md
    - Student Project:
        - Penetration Rate Experiments: student_project/numerical_data.md
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  language: en
  icon:
    repo: fontawesome/brands/github
    
  palette:
      # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
    
