site_name: Mixed Traffic Control
site_author: Yanzhi Yao
repo_url: https://github.com/soc-ucsd/mixed-traffic
edit_uri: edit/main/docs
nav:
    - Welcome: index.md
    - Smoothing traffic flow: smoothing_traffic_flow.md
    - Structured optimal control: structured_optimal_control.md
    - Cooperative formation multiple: cooperative_formation_multiple.md
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
